### ISSUE TITLE
API error

### ISSUE THREAD

**Issue by Mjssantana** [yadavgulshan/torrentstreamer#1]
Hello, there is a big inconsistency in the api.
Does the API contain a request limit?
I am available for any assistance.
![image](https://user-images.githubusercontent.com/79227431/159368266-78c85eb4-2b26-4de2-962e-514503cf4806.png)

**Comment by YadavGulshan** [comment]
Actually the API is down.
**Reason**: There're some changes in html structure of the pages from which the magnet links are getting scrapped from.
